### ISSUE TITLE
Enhancement: Update MacOS installer filename

### ISSUE THREAD

**Issue by RonanCodes** [Dinius/Brain.fm-Desktop-Client#13]
Change the name from:
`Brain.fm.app.zip`

to:
`brainfm-macos-zip`

In order to follow the naming convention used by the other installers.
This confused me when I first arrived at this page:
https://github.com/Dinius/Brain.fm-Desktop-Client/releases/tag/v0.1.5

**Comment by Dinius** [comment]
I actually thought that was a naming convention for MacOS, or even required. But turns out that's not the case. (I don't use macos so I'm not very familiar with such things). Updated it in the release.

**Comment by RonanCodes** [comment]
Thanks.
