### ISSUE TITLE
Player link has changed

### ISSUE THREAD

**Issue by havandenberg** [Dinius/Brain.fm-Desktop-Client#6]
The active link for the brain.fm player appears to be https://www1.brain.fm/app/player, not https://www.brain.fm/app/player as shown in the src code, so the app doesn't work for me :(.

**Comment by fcoury** [comment]
@havandenberg it still works fine for me. Can you send me a screenshot of what you get?

**Comment by havandenberg** [comment]
this is what i see:
![screen shot 2018-01-03 at 12 15 59](https://user-images.githubusercontent.com/8397680/34531342-f0dee6fe-f07f-11e7-9829-30fd71825cc0.png)

  and when I go to brain.fm player in my browser the link is on www1 not www. if I try to hit https://www.brain.fm/app/player it redirects me to https://www1.brain.fm/app/

**Comment by fcoury** [comment]
@havandenberg I updated the player link and still works for me. I added a pre-release binary here:

https://github.com/Dinius/Brain.fm-Desktop-Client/releases/tag/0.1.2-beta

see if it works for you now.

**Comment by havandenberg** [comment]
Niceee thank you yep its working now! :)

**Comment by fcoury** [comment]
@havandenberg thanks for checking. I'll go ahead and release this new version.

**Comment by fcoury** [comment]
Fixed by https://github.com/Dinius/Brain.fm-Desktop-Client/commit/f420cb9f592480f989af946ebb7bfafbae936606.
