### ISSUE TITLE
Sorry cant fint that!

### ISSUE THREAD

**Issue by dqhieu** [Dinius/Brain.fm-Desktop-Client#7]
Only this, anyone helps me?
![screen shot 2018-01-04 at 10 57 57 am](https://user-images.githubusercontent.com/8291457/34549841-5fd538d8-f13e-11e7-9997-a82d0c651cbc.png)

(already connected to the internet)

**Comment by fcoury** [comment]
Are you using the 0.1.2 release?

**Comment by dqhieu** [comment]
@fcoury OMG. I downloaded it yesterday. You just upload new version 0.1.2 :D
