### ISSUE TITLE
Can't copypaste password username

### ISSUE THREAD

**Issue by dtolb** [Dinius/Brain.fm-Desktop-Client#8]
Can't copy past account information in the login screen.

Steps to reproduce:
* Download latest [0.1.2](https://github.com/Dinius/Brain.fm-Desktop-Client/releases/tag/0.1.2)
* Ensure logged out
* Try to copy/paste username and password information into box

_side bar_ : love the app! Was looking for something exactly like this! 👍

**Comment by Maxim-Filimonov** [comment]
Same issue here - 0.1.2. Confusingly enough when app is not packaged it works - tried `npm start` on cloned repo.

---
See https://github.com/electron/electron/issues/2591
I'll try to take a swing at PR for this.

**Comment by fcoury** [comment]
Released 0.1.3 that fixes this. Thanks @Maxim-Filimonov!
